name: Sugar Cosmetics

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build for deployment
        run: npm run build  # Assuming your build command is `npm run build`

      - name: Deploy to GitHub Pages
        uses: actions/deploy-gh-pages@v4

